### ISSUE TITLE
6.3 release guzzle / php 7.0.20

### ISSUE THREAD

**Issue by leolems** [klarna/kco_rest_php#11]
Hi guys, this repo is very old... It uses old guzzle too
I want to use the newest versions, because our production environment is the newest php.

Can I even start developing with this?? or do i need to search for other payment providers.

Some help would be appreciated..

**Comment by bubach** [comment]
Here's a quick & dirty fix for Guzzle v6
https://github.com/Ridestore/kco_rest_php/commit/c71d4481176232bb46902705c270ac656ae01280

**Comment by leolems** [comment]
As much as I appreciate the "dirty" fix, it is really up to klarna to fix this!
I moved away from klarna.. because this old code doesnt feel like it is well maintained... :( 
I used another payment provider that actually does maintain its code

**Comment by adamskyle** [comment]
+1

If we cannot use this package out of the box (with PHP7 support), we won't implement Klarna Checkout in our new project.

**Comment by bubach** [comment]
Give em a break, it's not like they have houndreds of developers... oh w8.

**Comment by Almusamim** [comment]
Why is klarna so bad with maintaining their codes here?
3 years is a long time for no updates :(

**Comment by karaaie** [comment]
Since the sdk is not updated, might I suggest that you take a look at the API docs here instead? https://developer.klarna.com/api/#order-management-api that documentation is updated weekly and so you can just use a simple REST-client to consume it :)

**Comment by mitemitreski** [comment]
@leolems  @kyle51north  we are looking into adding a better support for this or creating a different solution.  For now if there is a major unsupported feature the only simple option is as @karaaie  suggested and use https://developer.klarna.com/api/

**Comment by mitemitreski** [comment]
@leolems  @kyle51north 

Fixed with @0x20h  PR. to be released as soon as possible
