### ISSUE TITLE
Create session for klarna payment integration issue

### ISSUE THREAD

**Issue by AmiluA** [klarna/kco_rest_php#14]
We are unable to get the create session reponse during klarna payment integration , because of the incorrect value generation of authorization parameter in create session step. The authorization parameter calculation is basis on : base64(hex(sha256 (request_payload + shared_secret))) .   We need clear describition about each and every variable used for authorization key generation .

What does the base64 means ? Is it base64_encode or base64_decode?
What you mean by hex() , sha256() and request_payload?

**Comment by richardhj** [comment]
From what I can tell, you are referencing to the Authorization of the Klarna Checkout v2, however, this is the repository for the Klarna Checkout v3.
Depending on your needs, whether you want to use [v2](https://github.com/klarna/kco_php) or v3, you can follow the examples within the `docs/` directory and don't need to worry about the Authorization header as it gets set by the SDK.
FYI, this is how it is done in the KCO v2 SDK: https://github.com/klarna/kco_php/blob/v4.0/src/Klarna/Checkout/Digest.php#L51

**Comment by 0x20h** [comment]
Thanks for triaging @richardhj.
