### ISSUE TITLE
Discount % applied to discounts on pre-4.0 after 4.0 was released.

### ISSUE THREAD

**Issue by tmikaeld** [klarna/kco_rest_php#19]
Seems like you changed something in the API, because right now discounts are getting discount applied to discounts.

Example of the issue:

![image 2018-10-31 at 11 40 57 am](https://user-images.githubusercontent.com/907195/47783006-ef0b4880-dd01-11e8-89f4-b270c8c4f9b0.png)

Previously before you released 4.0 it worked as expected:

![image 2018-10-31 at 11 42 26 am](https://user-images.githubusercontent.com/907195/47783067-1feb7d80-dd02-11e8-879c-ec5717a3c592.png)

Code used:

![image 2018-10-31 at 11 40 04 am](https://user-images.githubusercontent.com/907195/47783030-fb8fa100-dd01-11e8-9bfa-6c79f42a6ec9.png)

You cannot resonably expect us to rewrite our integrations the same day you release 4.0.

**Comment by alexions** [comment]
Hi @tmikaeld ,

Thank you for the report. I have some questions about your issue.

First: The SDK was not actually changed. The main changes - we added support of additional APIs. The Checkout and Order Management APIs were not changed.

Can you please describe in more details the issue? I assume you use Klarna Checkout API, right?

How can I reproduce the issue? Which data should I send to the Checkout API?

Thanks.

**Comment by tmikaeld** [comment]
My mistake, it was an older implementation different from checkout.

We've implemented both php-xmlrpc and checkout, the issue has been corrected.

Thanks for the swift reply!
