### ISSUE TITLE
"getenv" function is not working !

### ISSUE THREAD

**Issue by ghanshyamtank59** [klarna/kco_rest_php#29]
I am using this library in laravel framewok 5.5. The problem is, I have set "DEBUG_SDK" as false in my .env (environment) file. but it is not reflecting in this library file (klarna/kco_rest/src/Klarna/Rest/Resource.php). because of getenv function is not working.

Note: Currently, env() function is used instead of getenv().

**Comment by alexions** [comment]
Hi @ghanshyamtank59 

I'm not sure if I get your issue clearly. You tried to set DEBUG_SDK as "false", but it is still true. Right?

Talking about the env() vs getenv(). getenv() is native PHP function, but env() is laravel's one.
We cannot use more dependencies, that necessary. 

Could you provide more details about your problem? What exactly went wrong?

Thanks!

**Comment by alexions** [comment]
Hi @ghanshyamtank59 

Unfortunately there is no information from you for a long time. I will close the ticket for now. 
Please, feel free to reopen the ticket if you have more details.

Thanks!
