### ISSUE TITLE
Has this always been for Klarna v3?

### ISSUE THREAD

**Issue by x0nium** [klarna/kco_rest_php#34]
There is a Klarna Checkout module using this SDK, released in 2016, by Klarna for Opencart here: https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=27099

I have asked Klarna customer service whether that module is for Klarna v2 or v3, but they can't anwer that question.

Now that I see that this SDK is for Klarna v3, I would assume that module is as well. But has this SDK always been for Klarna v3? 

I hope someone here can answer whether that module was/is for v2 or v3?

**Comment by alexions** [comment]
Hi @x0nium 

Unfortunately, I have no source code for OpenCart add-on, so I cannot tell you which API version is in use, but I read some comments below and looks like this add-on uses the Klarna API v3: https://developers.klarna.com/api

My assumptions based on these parts:
1) composer require "klarna/kco_rest"
2) Fatal error: Class 'Klarna\Rest\Transport\ConnectorInterface' not found in 

kco_rest - is the API v3 SDK.
and ConnectorInterface is using for the API v3 also.
