### ISSUE TITLE
Caught exception: Response is missing a Content-Type header

### ISSUE THREAD

**Issue by pflind** [klarna/kco_rest_php#44]
Klarna Checkout API is throwing error with valid code example.

**This block of code seems to be causing the error.** If you remove this block from the example below the checkout is rendering without errors:
`    "options" => [
        "additional_checkbox" => [
            "text" => "Please add me to the newsletter list, read more here link",
            "checked" => false,
            "required" => false
        ],
    ],`

**Error thrown:**
`Caught exception: Response is missing a Content-Type header`

**Reproduce with this full example.**
```
$merchantId = '';
$sharedSecret = '';

$apiEndpoint = Klarna\Rest\Transport\ConnectorInterface::EU_TEST_BASE_URL;

// Create cURL HTTP Transport Connector
$connector = Klarna\Rest\Transport\CURLConnector::create($merchantId,$sharedSecret,$apiEndpoint);

$order = [
    "purchase_country" => "se",
    "purchase_currency" => "sek",
    "locale" => "sv-se",
    "order_amount" => 12750,
    "order_tax_amount" => 2550,

    "order_lines" => [
        [
            "type" => "physical",
            "reference" => "abc123",
            "name" => "Product Name",
            "quantity" => 1,
            "unit_price" => 10000,
            "tax_rate" => 2500,
            "total_amount" => 10000,
            "total_tax_amount" => 2000
        ],
        [
            "type" => "discount",
            "reference" => "discount50",
            "name" => "Discount 50%",
            "quantity" => 1,
            "unit_price" => -5000,
            "tax_rate" => 2500,
            "total_amount" => -5000,
            "total_tax_amount" => -1000
        ],
        [
            "type" => "shipping_fee",
            "reference" => "shipping",
            "name" => "Shipping",
            "quantity" => 1,
            "unit_price" => 7750,
            "tax_rate" => 2500,
            "total_amount" => 7750,
            "total_tax_amount" => 1550
        ],
    ],

    "options" => [
        "additional_checkbox" => [
            "text" => "Please add me to the newsletter list, read more here link",
            "checked" => false,
            "required" => false
        ],
    ],

    "merchant_urls" => [
        "terms" => "http://www.merchant.com/toc",
        "checkout" => "http://www.merchant.com/checkout?klarna_order_id={checkout.order.id}",
        "confirmation" => "http://www.merchant.com/thank-you?klarna_order_id={checkout.order.id}",
        "push" => "http://www.merchant.com/create_order?klarna_order_id={checkout.order.id}"
    ],

];

try {
    $checkout = new Klarna\Rest\Checkout\Order($connector);
    $checkout->create($order);

    // Store checkout order id
    $orderId = $checkout->getId();

    // Get some data if needed
    echo <<<ORDER
         OrderID: $checkout[order_id]
    Order status: $checkout[status]
    HTML snippet: $checkout[html_snippet]
ORDER;
} catch (Exception $e) {
    echo 'Caught exception: ' . $e->getMessage() . "\n";
}
```

**Comment by alexions** [comment]
Thank you for the report. I'm checking this issue.

**Comment by alexions** [comment]
I've checked the exact code you posted and unfortunately cannot reproduce the issue. The response that I have looks good.

Could you enable the DEBUG_SDK and provide the debugging output? https://github.com/klarna/kco_rest_php#logging-and-debugging

I think the problem can be caused by authorization or a playground API server glitch. Anyway, having the debug out will help to understand the problem.

Thanks!

**Comment by pflind** [comment]
@alexions 

Here's the debug response:

`>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> POST : /checkout/v3/orders Headers : {"Content-Type":"application\/json"} Body : {"purchase_country":"se","purchase_currency":"sek","locale":"sv-se","order_amount":12750,"order_tax_amount":2550,"order_lines":[{"type":"physical","reference":"abc123","name":"Product Name","quantity":1,"unit_price":10000,"tax_rate":2500,"total_amount":10000,"total_tax_amount":2000},{"type":"discount","reference":"discount50","name":"Discount 50%","quantity":1,"unit_price":-5000,"tax_rate":2500,"total_amount":-5000,"total_tax_amount":-1000},{"type":"shipping_fee","reference":"shipping","name":"Shipping","quantity":1,"unit_price":7750,"tax_rate":2500,"total_amount":7750,"total_tax_amount":1550}],"options":{"additional_checkbox":{"text":"Please add me to the newsletter list, read more here link","checked":false,"required":false}},"merchant_urls":{"terms":"http:\/\/www.merchant.com\/toc","checkout":"http:\/\/www.merchant.com\/checkout?klarna_order_id={checkout.order.id}","confirmation":"http:\/\/www.merchant.com\/thank-you?klarna_order_id={checkout.order.id}","push":"http:\/\/www.merchant.com\/create_order?klarna_order_id={checkout.order.id}"}} DEBUG MODE: Response <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Headers : {"Http":"HTTP\/1.1 100 Continue"} Body : HTTP/1.1 201 Created Date: Mon, 14 Oct 2019 16:51:38 GMT Content-Type: application/json Content-Length: 4947 Connection: keep-alive Server: openresty Cache-Control: max-age=0, no-cache, no-store Pragma: no-cache Klarna-Correlation-Id: 6f485aa7-da9e-4f4a-845d-fb6ed0b90a98 Location: https://api.playground.klarna.com/checkout/v3/orders/269f158a-7988-5075-a7f8-c9c19224dfa4 Render-Time: 8 Strict-Transport-Security: max-age=31536000; includeSubDomains {"order_id":"269f158a-7988-5075-a7f8-c9c19224dfa4","status":"checkout_incomplete","purchase_country":"se","purchase_currency":"sek","locale":"sv-SE","billing_address":{"country":"se"},"customer":{},"shipping_address":{"country":"se"},"order_amount":12750,"order_tax_amount":2550,"order_lines":[{"type":"physical","reference":"abc123","name":"Product Name","quantity":1,"unit_price":10000,"tax_rate":2500,"total_amount":10000,"total_discount_amount":0,"total_tax_amount":2000},{"type":"discount","reference":"discount50","name":"Discount 50%","quantity":1,"unit_price":-5000,"tax_rate":2500,"total_amount":-5000,"total_discount_amount":0,"total_tax_amount":-1000},{"type":"shipping_fee","reference":"shipping","name":"Shipping","quantity":1,"unit_price":7750,"tax_rate":2500,"total_amount":7750,"total_discount_amount":0,"total_tax_amount":1550}],"merchant_urls":{"terms":"http://www.merchant.com/toc","checkout":"http://www.merchant.com/checkout?klarna_order_id={checkout.order.id}","confirmation":"http://www.merchant.com/thank-you?klarna_order_id={checkout.order.id}","push":"http://www.merchant.com/create_order?klarna_order_id={checkout.order.id}"},"html_snippet":"
\n
\n \n
Oops.

\n
It looks like an important part of the checkout experience failed to load and we are unable to offer you a way to pay right now.

\n
Please refresh the page to try again. If this isn't the first time you've seen this message then there may be a more permanent error and you should contact customer service at Klarna.com.

\n
\n \n \n
","started_at":"2019-10-14T16:51:38Z","last_modified_at":"2019-10-14T16:51:38Z","options":{"allow_separate_shipping_address":false,"date_of_birth_mandatory":false,"additional_checkbox":{"text":"Please add me to the newsletter list, read more here link","checked":false,"required":false},"require_validate_callback_success":false},"external_payment_methods":[],"external_checkouts":[]} Caught exception: Response is missing a Content-Type header`

**Comment by alexions** [comment]
Thanks @pflind for the provided information. This info helped me to understand the issue.

This issue is a combination of multiple factors:
1) Server/env configuration
2) Headers processing in the SDK

Looks like your server/environment has a limitation on the HTTP protocol version. By default CURL tries to use the latest available HTTP protocol, which is currently HTTP2

```
* SSL connection using TLSv1.2
* SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fde11006400)
> POST /checkout/v3/orders HTTP/2
```

In your case you cannot upgrade connection to HTTP2 and your curl library uses HTTP1.1
```
* SSL connection using TLSv1.2
* SSL certificate verify ok.
> POST /checkout/v3/orders HTTP/1.1
```

The [RFC2616](https://tools.ietf.org/html/rfc2616#section-8.2.3) says, that when sending POST requests with HTTP1.1 you should send an Expect header in order to pre-validate the request body. CURL follows this RFC and sends it if the request body is bigger that 1k.

But based on this pre-validation server must send 2 responses (actually 2 headers): one with HTTP/1.1 100 Continue in order to confirm that we can send the body and the second one with the actual HTTP response code.

In the SDK parser we rely only on the first headers part and not on the second one and this created the issue you reported. 

You can check the fix we're going to release.

Thank you one more time for the provided feedback!
