### ISSUE TITLE
PSR4 autoload definition is defined as fallback directory

### ISSUE THREAD

**Issue by bkonetzny** [klarna/kco_rest_php#46]
**Describe the bug**
Current definition of autoload in composer.json (`"autoload":{"psr-4":{"":"src/"}}`) causes composer to use this as a fallback directory for all classes to look up (see https://getcomposer.org/doc/04-schema.md#psr-4).

**Expected behavior**
Defining the Klarna namespace according to the correct directory, as all classes are namespaced with Klarna/, this config would work find and would prevent composer from using the `/klarna/kco_rest/src` directory as a fallback directory: `"autoload":{"psr-4":{"Klarna\\":"src/Klarna/"}}`

**Comment by alexions** [comment]
Available in v4.2.2
