### ISSUE TITLE
URI's for Live environment & Testing environment are not working. 

### ISSUE THREAD

**Issue by ImranLashari123** [klarna/kco_rest_php#48]
**Describe the bug**
i am using PHP LAravel 5.8. I want to test klarna payment method but Getting 404 error on https://api-na.klarna.com/ and https://api-na.playground.klarna.com/ 

**Which service do you use**
 Klarna Checkout

**Comment by beije** [comment]
I'm seeing this issue too (although it worked last week), getting 404 from the klarna API. I'm not seeing any issues  on the [klarna status page](https://status.klarna.com/)

    RuntimeException: Unexpected reponse HTTP status 404. Excepted HTTP status should be in 2xx range in file vendor/klarna/kco_rest/src/Klarna/Rest/Transport/ResponseValidator.php on line 195

**Comment by freethan** [comment]
Hi there @ImranLashari123 please verify that you have created credentials the US environment you want to connect to. Production credentials are only given out if you have completed the production onboarding, meaning you have a contract with Klarna.

https://developers.klarna.com/documentation/testing-environment/ has links to both EU / US "playground" environment onboarding processes.

After going through the process for the target environment, you should be able to see your credentials on the Merchant Portal:

US Playground
https://playground.us.portal.klarna.com/settings/credentials

EU Playground
https://playground.eu.portal.klarna.com/settings/credentials

Let me know if this helps,
Regards

**Comment by freethan** [comment]
> I'm seeing this issue too (although it worked last week), getting 404 from the klarna API. I'm not seeing any issues on the [klarna status page](https://status.klarna.com/)
> 
> ```
> RuntimeException: Unexpected reponse HTTP status 404. Excepted HTTP status should be in 2xx range in file vendor/klarna/kco_rest/src/Klarna/Rest/Transport/ResponseValidator.php on line 195
> ```

Hi there @beije can you provide some more information in order to reproduce this issue? 

- What environment were you targeting at the time ?
- What environment are your credentials valid for ?
- What API / endpoint specifically were you trying to access at the time ?

**Comment by beije** [comment]
> > I'm seeing this issue too (although it worked last week), getting 404 from the klarna API. I'm not seeing any issues on the [klarna status page](https://status.klarna.com/)
> > ```
> > RuntimeException: Unexpected reponse HTTP status 404. Excepted HTTP status should be in 2xx range in file vendor/klarna/kco_rest/src/Klarna/Rest/Transport/ResponseValidator.php on line 195
> > ```
> 
> Hi there @beije can you provide some more information in order to reproduce this issue?
> 
>     * What environment were you targeting at the time ?
> 
>     * What environment are your credentials valid for ?
> 
>     * What API / endpoint specifically were you trying to access at the time ?

@freethan I'm working with klarna checkout, and I have credentials for that as well, and it has been working since august until last Friday. (haven't tried it this week until today).

The problem occurs (getting a 404) when I'm trying to create a checkout order.

The API is the european playground, https://api.playground.klarna.com

**Comment by ImranLashari123** [comment]
> > I'm seeing this issue too (although it worked last week), getting 404 from the klarna API. I'm not seeing any issues on the [klarna status page](https://status.klarna.com/)
> > ```
> > RuntimeException: Unexpected reponse HTTP status 404. Excepted HTTP status should be in 2xx range in file vendor/klarna/kco_rest/src/Klarna/Rest/Transport/ResponseValidator.php on line 195
> > ```
> 
> Hi there @beije can you provide some more information in order to reproduce this issue?
> 
> * What environment were you targeting at the time ?
> * What environment are your credentials valid for ?
> * What API / endpoint specifically were you trying to access at the time ?

Dear i have done the process which you have mentioned... and how 404 error  can be linked with signup? its separate thing. so problem is that links are not working...!!!

**Comment by alexions** [comment]
Hi @ImranLashari123 

I just re-checked both **NA** URLs https://api-na.klarna.com/ and https://api-na.playground.klarna.com/ and it seems everything works well now. (Note: By clicking the URLs you will get 404. The SDK uses extra paths to work with API Entities)

Unfortunately, I cannot confirm or deny the system status health at those time, so I can just suggest you to test it one more time.

From my side I was able to reach the `ConnectorInterface::NA_TEST_BASE_URL` and `ConnectorInterface::NA_BASE_URL` without any problems.

Feel free to reopen the issue if you still experience the issue.

Thanks!
