### ISSUE TITLE
Missing expected return from distrubuting link

### ISSUE THREAD

**Issue by dcolt** [klarna/kco_rest_php#52]
**Describe the bug**
Throws exception on 204 return when distributing link.

**Which service do you use**
Example: Klarna HostedPaymentPage

**To Reproduce**
1. Create a Payment Session in Test envirorment
2. Create a HPP for that Payment session
3. Use HPP distributeLink
4. See error (link still gets sent)

**Expected behavior**
Silent return with no throw.

**Additional context**
Issue gets fixed by adding `204` to the expected statuses in `src/Klarna/Rest/HostedPaymentPage/Session.php line 132`

**Comment by alexions** [comment]
https://github.com/klarna/kco_rest_php/pull/53

**Comment by alexions** [comment]
Thank you for the proposed fix. I can confirm, that distribution link endpoint returns 204 instead of 201.

**Comment by alexions** [comment]
Your PR has been merged. The fix will be available in the next release
